export {
  auth,
  onAuthStateChanged,
  signInWithGoogle,
  signInWithEmailAndPassword,
  signUpWithEmailAndPassword,
  sendPasswordResetEmail,
  signOut,
  getCurrentUserToken,
  getCurrentUserEmail,
  getCurrentUser,
  updateUserEmail,
  UpdateUserPassword,
  reauthenticate,
} from "./auth";
