export const POST_SONG_REQUEST = "POST_SONG_REQUEST";
export const POST_SONG_SUCCESS = "POST_SONG_SUCCESS";
export const POST_SONG_FAIL = "POST_SONG_FAIL";
export const GET_MY_SONGS_REQUEST = "GET_MY_SONGS_REQUEST";
export const GET_MY_SONGS_SUCCESS = "GET_MY_SONGS_SUCCESS";
export const GET_MY_SONGS_FAIL = "GET_MY_SONGS_FAIL";
export const UPDATE_SONG_REQUEST = "UPDATE_SONG_REQUEST";
export const UPDATE_SONG_SUCCESS = "UPDATE_SONG_SUCCESS";
export const UPDATE_SONG_FAIL = "UPDATE_SONG_FAIL";

export const LIKE_SONG_REQUEST = "LIKE_SONG_REQUEST";
export const LIKE_SONG_SUCCESS = "LIKE_SONG_SUCCESS";
export const LIKE_SONG_FAIL = "LIKE_SONG_FAIL";

export const CANCEL_LIKED_SONG_REQUEST = "CANCEL_LIKED_SONG_REQUEST";
export const CANCEL_LIKED_SONG_SUCCESS = "CANCEL_LIKED_SONG_SUCCESS";
export const CANCEL_LIKED_SONG_FAIL = "CANCEL_LIKED_SONG_FAIL";

export const GET_MY_LIKED_SONGS_REQUEST = "GET_MY_LIKED_SONGS_REQUEST";
export const GET_MY_LIKED_SONGS_SUCCESS = "GET_MY_LIKED_SONGS_SUCCESS";
export const GET_MY_LIKED_SONGS_FAIL = "GET_MY_LIKED_SONGS_FAIL";
