export const PLAYLIST_CREATE_REQUEST = "PLAYLIST_CREATE_REQUEST";
export const PLAYLIST_CREATE_SUCCESS = "PLAYLIST_CREATE_SUCCESS";
export const PLAYLIST_CREATE_FAIL = "PLAYLIST_CREATE_FAIL";

export const GET_PLAYLIST_REQUEST = "GET_PLAYLIST_REQUEST";
export const GET_PLAYLIST_SUCCESS = "GET_PLAYLIST_SUCCESS";
export const GET_PLAYLIST_FAIL = "GET_PLAYLIST_FAIL";

export const GET_MY_PLAYLISTS_REQUEST = "GET_MY_PLAYLISTS_REQUEST";
export const GET_MY_PLAYLISTS_SUCCESS = "GET_MY_PLAYLISTS_SUCCESS";
export const GET_MY_PLAYLISTS_FAIL = "GET_MY_PLAYLISTS_FAIL";

export const ADD_SONG_TO_PLAYLIST_REQUEST = "ADD_SONG_TO_PLAYLIST_REQUEST";
export const ADD_SONG_TO_PLAYLIST_SUCCESS = "ADD_SONG_TO_PLAYLIST_SUCCESS";
export const ADD_SONG_TO_PLAYLIST_FAIL = "ADD_SONG_TO_PLAYLIST_FAIL";
