export const PLAY_REQUEST = "PLAY_REQUEST";
export const PLAY_SUCCESS = "PLAY_SUCCESS";
export const PLAY_FAIL = "PLAY_FAIL";

export const PLAY_NEXT_REQUEST = "PLAY_NEXT_REQUEST";
export const PLAY_NEXT_SUCCESS = "PLAY_NEXT_SUCCESS";
export const PLAY_NEXT_FAIL = "PLAY_NEXT_FAIL";

export const PLAY_PREV_REQUEST = "PLAY_PREV_REQUEST";
export const PLAY_PREV_SUCCESS = "PLAY_PREV_SUCCESS";
export const PLAY_PREV_FAIL = "PLAY_PREV_FAIL";
